### ISSUE TITLE
Features task list

### ISSUE THREAD

**Issue by prowe12** [prowe12/cambio#17]
Planned
- [x] Disallow line wrap between check box and variable to plot.
- [x] Remove "Include noise" boolean because the user can set the noise level to 0.
- [x] Make arrows prettier in labels.
- [x] Make blue color on web page go all the way to bottom
- [x] Remove extra horizontal line at bottom of page.
- [x] Fix issue where adding a new scenario resets the plots to the defaults.
- [x] Remove extra variables (start/stop year, dtime etc) for added scenarios
- [x] change update plots to a floating button or make it always available
- [x] Use display variables for added scenarios.
- [ ] Determine how to handle case when user enters characters for number.
- [ ] Add action to auto-deploy to fly on merge
- [ ] Add releases/tags.
- [ ] Fix styling on various browsers
- [ ] Add radio button for cases with no units showing, or delete word "Units"

Bug fix:
- [x] The delete button next to scenarios is automatically checked when the plot button is clicked.
- [x] Scenarios checked for deletion are deleted when the plot button is clicked.
- [ ] Uncontrolled error when user enters two-word scenario name.
- [ ] In the model, fix strange behavior when noise is very high, or disallow high noise.

Wish list:
- [x] Remove albedo feedback input (T/F) and instead add user input albedo tipping point temperature.
- [x] Remove forest fire feedback input (T/F) and instead add user input forest tipping point temperature.
- [x] For both, make the default “True”, with values ~4 degrees.
- [x] Include tipping point temperatures on plots
- [ ] Add ability to rename scenarios 
- [ ] Add ability to modify an existing scenario
- [ ] Add notes elaborating on scenarios
- [ ] Supply default names for new scenarios (rather than “default”)
- [ ] When curves are right on top of one another, differentiate them (by making curve in back thicker)
- [ ] Add option to upload inputs
- [ ] Add option to download results
- [ ] Get rid of the noise option for the user, or show mean and std deviation for many runs
